##================= Spring Boot日志配置  ====================
# 开启debug模式
#debug : true
logging :
  level :
    root : INFO # 配置Root Logger级别
    com :
      zerod :
        codemonkey : 
          mapper : DEBUG # MyBatis SQL日志
##=================   Spring配置        ====================
spring :
  resources :
    static-locations : # 静态资源位置
      - classpath:/html
      - classpath:/js
      - classpath:/css
  jackson :
    serialization : 
      INDENT_OUTPUT : true # 漂亮的输出JSON
  freemarker :
    templateLoaderPath : classpath:/templates/ # FreeMarker模板目录
    prefix :      # 模板前缀
    suffix : .ftl # 模板后缀
  datasource :
      url : jdbc:mysql://localhost:3306/information_schema?useSSL=false # 数据源连接地址
      username : root # 用户名
      password : root # 密码
##=================   MyBatis配置        ====================
mybatis :
  mapper-locations : classpath:com/zerod/codemonkey/mapper/*Mapper.xml # Mapper文件位置
  type-aliases-package : com.zerod.codemonkey.entity # 别名类型包 
  configuration :
    database-id : mysql # mysql
    mapUnderscoreToCamelCase : true # 列名到Java属性名自动映射
##=================  CodeMonkey配置     ====================
codemonkey :
  table-schema : mantianxing # 数据库名称
  table-prefix : t_ # 表前缀
  entity-name-rm-prefix : true # 实体名称是否删除表前缀
  base-package : com.zerod.codemonkey # 基础包名
  base-path : E:/code # 代码生成目录
  template-names : # 模板名称列表
    - mapper_xml